### ISSUE TITLE
Any interest in joining the trac-hacks organization?

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/ticket2rtm#2]
Hi,

I'm an administrator for trac-hacks.org.  We've created an organization on GitHub and are inviting authors of trac-hacks plugins to join the organization.  Your repository could be transferred into the organization as described in the [GitHub docs](https://help.github.com/articles/transferring-a-repository/).  You'd retain full control over the repository, but the hope is that it will be easier for users on GitHub to fine trac-hacks plugins, including yours, by viewing the trac-hacks organization.

In the future, if you choose to no longer maintain the plugin, the organization would be able to provide commit access to new developers.  This would only be done with your permission, as has been the policy for plugins hosted on trac-hacks.org.  If you've already decided to no longer maintain the plugin, we would particularly appreciate you transferring the plugin to the trac-hacks organization so that we can help find new maintainers for it.

Finally, creating the trac-hacks organization is a work in progress. I appreciate if you have any suggestions on how to best support the community of trac plugin developers on GitHub. I'll be writing a blog post soon with more information and will follow-up here with a link to that post.

Kind regards,
- Ryan

**Comment by mootoh** [comment]
@rjollos, Since I no longer maintain this plugin, I'm happy to transfer the repo to the organization. Just let me know if the organization is ready.

Thanks for reaching me,

**Comment by rjollos** [comment]
Thanks! You should receive an invite to join the trac-hacks organization. You'll have general Admin access to the trac-hacks organization which will allow you to execute [these steps](https://help.github.com/articles/transferring-a-repository/#transferring-between-user-accounts) and transfer the repository. After you transfer the repository I'll remove you from the Admin team, create an Admin group for your repository and make you the Admin for your repository.

**Comment by mootoh** [comment]
The repository has been transferred to the organization :)

**Comment by rjollos** [comment]
Looks good. Thanks!
